name: Dr Mind Fuck
favicon: null
layout_spectrum: 0.9925090130418539
typography_spectrum: 0.16393022215925157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6813848344609141
  lightness: 0.9248469606973231
  saturation: 0.7036842668894678
  rhythmicContrast: 0.4986491263844073
purpose: []
